# Generated by Django 4.0.6 on 2022-08-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
        ('cars_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealership'),
        ),
    ]
